imagePullPolicy: Always
image: prague.azurecr.io/pythontutor:latest
name: pythontutor
replicas: 1

host: pythontutor.wu2-2.prague.office-int.com
cert: wu2-2-tls-certificate
ingressClass: nginx-prod

logger:
  colorize: false
  morganFormat: "short"
  json: true
  level: "info"
  timestamp: false
  label: "winston"

requestSizeLimit: 1gb
