apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pythontutor.fullname" . }}
  labels:
    app: {{ template "pythontutor.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {{ toJson .Values.logger }},
        "npm": {{ toJson .Values.npm }},
        "requestSizeLimit": "{{ .Values.requestSizeLimit }}"
    }