apiVersion: v1
kind: Service
metadata:
  name: {{ template "pythontutor.fullname" . }}
  labels:
    app: {{ template "pythontutor.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: http
      port: 8003
      targetPort: http
  type: ClusterIP
  selector:
    app: {{ template "pythontutor.fullname" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}